### ISSUE TITLE
Creating a TOC with a numbered index (2 new potential options)

### ISSUE THREAD

**Issue by nickjj** [Scuilion/markdown-drawer#1]
I would really like to see 2 new options around indexing the headers.

Here's a couple of examples to describe the use case / feature request:

---

`test.md`
```
# Example
## Hello World
# Another Section
## Cool Story
## Thanks for Reading
```

---

##### Current output

```
Example
  Hello World
Another Section
  Cool Story
  Thanks for Reading
```

---

##### New option with an index

```
1. Example
  1. Hello World
2. Another Section
  1. Cool Story
  2. Thanks for Reading
```

I often want to be able to see this style of TOC. I'm a course creator and the L1 headings are sections while the L2 headings are lessons. Being able to see at a glance how many sections I have, and how many lessons are in each section is a huge win.

---

##### New option with a more customized index

```
1. Example
  1. Hello World
2. Another Section
  2. Cool Story
  3. Thanks for Reading
```

Unlike the previous example, instead of each section having its own separately indexed lessons, now the lessons are indexed from top to bottom across all sections. This is very very handy to have because now I can see how many lessons I have total, and then tie in those numbers to reference other things that I need to do outside of Vim.

Maybe the option could let you pick which heading level to tally (1-6) and then that level along with all previous levels are tallied individually. I'm not exactly sure how it could work in a general case.

---

What do you think? Also for clarity, these index numbers wouldn't be in the "real" markdown file. They would be auto-updated indexes that are only shown in the TOC.

**Comment by Scuilion** [comment]
@nickjj I've made a first pass at this.

[https://github.com/Scuilion/markdown-drawer/commit/0551ef3957daee206ed79dea648249f5cac6eb29](indexing)

set:
`g:markdrawer_toc = 'index'` for relative indexing.
or
`g:markdrawer_toc = 'full_index'`

Just a note, the `index` implementation does not understand "implicit terms". Example:
```
# level-one
### level-three topic one
### level-three topic  two
## level-two topic 
```
is generally represented as: 
```
1. level-one
   1. level-three topic one
   2. level-three topic one
  2. level-two topic 
```
This is because the "level-three" section is considered to live under the un-listed "level-two" term.

~~I haven't tested performance against large files.~~ Tested, works fine.
