### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by WaterSibilantFalling** [Scuilion/markdown-drawer#5]
If I change the markdown doc's headings, say remove or add one, how do I get the markdown drawer window to recalculate, to show the changed headings? 

I can't see in the screen capture: What key moves the cursor from a heading in the markdown file to the matching header in the markdown drawer?

**Comment by Scuilion** [comment]
In order to move from the file to the drawer you can use the following ex command.
`:MarkdownDrawer`

In my .vimrc file, I've created a mapping to this ex command so that when I press `<Leader>md` the drawer will open.
`nnoremap <Leader>md :MarkDrawer<cr>`

The drawer will refresh whenever this command is run.

**Comment by WaterSibilantFalling** [comment]
Thank you.
